# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["you@example.com"]
description = "An app for learning about status codes"
language = "javascript"
manifest_version = 3
name = "keanu-home"
service_id = "YAbz4BcxwouqqJgoVMCm66"

[local_server]

  [local_server.kv_stores]

    [local_server.kv_stores.keanu-content]
      file = "./static-publisher/kvstore.json"
      format = "json"

[scripts]
  build = "npm run build"

[setup]

  [setup.kv_stores]

    [setup.kv_stores.keanu-content]
